var k=void 0,n=!0,q=null,t=!1;
define("tiles_factory",[],function(){function c(a,i,f){var d,e,b,h;if(i.j!==a.j||i.l!==a.l)return t;for(d=0;d<i.length;d+=1){b=i[d];h=a[d];for(e=0;e<b.length;e+=1)if(!f(b[e],h[e]))return t}return n}var g;g=Object.create([],{Q:{value:function(a){return c(this,a,function(a,f){return a===f})}},T:{value:function(a){return c(this,a,function(a,f){return a.color===f.color})}},j:{get:function(){return this.length}},l:{get:function(){return 0<this.j?this[0].length:0}},copy:{value:function(){var a=Object.create(g);
this.forEach(function(g){a.push(g.slice())});return a}}});return Object.create(q,{load:{value:function(a,i){var f=new Image;f.onload=function(){var a=document.createElement("canvas"),e=a.getContext("2d");a.width=f.width;a.height=f.height;e.drawImage(f,0,0);var b,h,c,j,a=Math.min(f.width,f.height),l=e.getImageData(0,0,a,a).data,e=Object.create(g);for(h=0;h<a;h+=1){b=[];for(c=0;c<a;c+=1)j=4*(c*a+h),b.push({color:"rgb("+l[j]+","+l[j+1]+","+l[j+2]+")"});e.push(b)}i(e)};f.src=a}}})});
define("hiscores_factory",[],function(){var c=[{name:"Roger",b:6},{name:"Larry",b:8},{name:"Zak",b:9},{name:"Mario",b:10},{name:"Gianna",b:11},{name:"Sonya",b:30},{name:"Johnny",b:42}].slice(0,7),g="";return Object.create(q,{load:{value:function(a,i){var f,d=q;f=c.slice();i(Object.create(q,{forEach:{value:function(a){var b,h,c=f.length,g=t;for(b=0;b<c;b+=1)h=f[b],d!==q&&d.b<=h.b&&!g?(a(d,b,n),b-=1,c-=1,g=n):a(h,b,t)}},H:{get:function(){return 8}},I:{set:function(a){d!==q&&(a=a.substring(0,this.H),
g=d.name=a)}},ea:{value:function(){if(d!==q){a:{var a=d,b,h,c=t;if(""!==a.name)for(b=0;b<f.length;b+=1){h=f[b];if(a.name===h.name&&a.b>=h.b)break a;a.b<=h.b&&!c?(f.splice(b,0,a),c=n):a.name===h.name&&f.splice(b,1)}f.length=Math.min(f.length,7)}d=q}}},ba:{value:function(a){d={name:g,i:a.slice(),b:a.length}}},da:{value:function(){d=q}}}))}}})});
define("board_factory",["tiles_factory","hiscores_factory"],function(c,g){function a(a){return a.g!==k&&a.D!==k&&a.h!==k}function i(a,b){Object.defineProperty(a,"sideLenT",{value:a.g.length});b(a)}function f(a,b,f,c){return a[f][c-b]}function d(a,b,f,c,e){return a[e-f][b]}function e(a,b,f,c,e){return a[c-b][e-f]}function b(a,b,f){var c,e,h=b[0][0],d=b[0][1],g=b[1][0],b=b[1][1],i=g-h,s=b-d,j,x;j=[];for(e=h;e<=g;e+=1){c=[];for(x=d;x<=b;x+=1)c.push(a[e][x]);j.push(c)}for(c=h;c<=g;c+=1)for(e=d;e<=b;e+=
1)a[c][e]=f(j,c-h,e-d,i,s)}function h(a,c){var h=c.e,g=c.k;h.u?g?b(a,h,f):b(a,h,d):b(a,h,e)}function s(a,b){b.g.T(b.D)?a.d||(a.d=n,b.h.ba(a.i)):(a.d=t,b.h.da())}var j;j=Object.create(q,{rotate:{value:function(a,b){a.i.push(b);a.p.length=0;h(this.g,b);s(a,this);a.m=b}},w:{value:function(a){var b=a.i.pop();b!==k&&(a.p.push(b),h(this.g,b.inverse),s(a,this),a.m=b.inverse)}},v:{value:function(a){var b=a.p.pop();b!==k&&(a.i.push(b),h(this.g,b),s(a,this),a.m=b)}}});return Object.create(q,{load:{value:function(b,
f){var e,h={i:[],p:[],m:q,d:t};e=Object.create(j,{rotate:{value:function(a){j.rotate.call(this,h,a)}},b:{get:function(){return h.i.length}},ga:{get:function(){return 0<h.i.length}},w:{value:function(){j.w.call(this,h)}},ca:{get:function(){return 0<h.p.length}},v:{value:function(){j.v.call(this,h)}},d:{get:function(){return h.d}},m:{get:function(){return h.m}}});c.load("boards/"+b+"/start.gif",function(b){Object.defineProperty(e,"tiles",{value:b});a(e)&&i(e,f)});c.load("boards/"+b+"/end.gif",function(b){Object.defineProperty(e,
"endTiles",{value:b});a(e)&&i(e,f)});g.load("boards/hiscores.json/undefined",function(b){Object.defineProperty(e,"hiscores",{value:b});a(e)&&i(e,f)})}}})});
define("boards",["board_factory"],function(c){var g=0,a,i="13 smiley sq house dogman rgbcmy invaders".split(" ");return a=Object.create([],{load:{value:function(f){this.length=i.length;i.forEach(function(d,e){c.load(d,function(b){a[e]=b;a:{for(b=0;b<i.length;b+=1)if(a[b]===k){b=t;break a}b=n}b&&f()})})}},selected:{get:function(){return this[g]}},L:{get:function(){return g},set:function(a){g=a}}})});
define("util",[],function(){return Object.create(q,{B:{value:function(c){"complete"===document.readyState?c():document.addEventListener("readystatechange",function(){"complete"===document.readyState&&c()})}},clear:{value:function(c){for(;c.firstChild;)c.removeChild(c.firstChild)}}})});
define("rect_t_factory",[],function(){var c,g;g=function(a,c){return a[0]===c[0]&&a[1]===c[1]};c=Object.create([],{q:{value:function(a){return g(this[0],a[0])&&g(this[1],a[1])}},j:{get:function(){return this[1][0]-this[0][0]}},l:{get:function(){return this[1][1]-this[0][1]}},S:{get:function(){return[(this[0][0]+this[1][0])/2,(this[0][1]+this[1][1])/2]}},contains:{value:function(a){var c=a[0],a=a[1];return c>=this[0][0]&&a>=this[0][1]&&c<=this[1][0]&&a<=this[1][1]}},u:{get:function(){return this.j===
this.l}}});return Object.create(q,{create:{value:function(a,g){var f=Object.create(c);f.push(a);f.push(g);return f}}})});
define("display_c_sys",["boards"],function(c){function g(){var b;i!==k&&(b=i.t,d=e?0:0.05*a/b,f=(a-d*(b+1))/b)}var a,i,f=0,d=0,e=t;return Object.create(q,{c:{set:function(b){b!==a&&(a=b,g())}},a:{value:function(){c.selected!==i&&(i=c.selected,g())}},s:{value:function(a){return a.map(function(a){return a*(f+d)+d})}},J:{value:function(a){return a.map(function(a){return(a-d)/(f+d)})}},U:{value:function(a){return a.map(function(a){var b=a%(f+d);return 0<a&&b<d?a-b-f/2:a})}},X:{value:function(a){return a.map(function(a){var b=
a%(f+d);return 0<a&&b<d?a-b+d+f/2:a})}},K:{value:function(a){return a.map(function(a){return Math.min(Math.max(a,0),i.t-1)})}},n:{get:function(){return f}},fa:{get:function(){return d}},V:{value:function(){e=n;g()}},W:{value:function(){e=t;g()}}})});
define("display_canvas_factory",[],function(){return Object.create(q,{create:{value:function(){var c=n,g=n;return Object.create(q,{A:{get:function(){return g}},r:{get:function(){return c}},z:{value:function(a){a.style.display=c?"block":"none";g=t}},show:{value:function(){c||(g=c=n)}},f:{value:function(){c&&(c=t,g=n)}}})}}})});
define("rubber_band_canvas",["util","rect_t_factory","display_c_sys","display_canvas_factory"],function(c,g,a,i){function f(){var b=a.X([Math.min(o[0],r[0]),Math.min(o[1],r[1])]),e=a.U([Math.max(o[0],r[0]),Math.max(o[1],r[1])]),b=a.K(a.J(b).map(Math.floor)),e=a.K(a.J(e).map(Math.floor));y=g.create(b,e)}function d(){D=r[0]>o[0]}function e(a){r=o=a;f();d();w=A=n;z!==k&&z()}function b(a){r=a;f();d();w=n;B!==k&&B(y,D)}function h(){A=t;w=n;o=r=[0,0];f();d();E!==k&&E()}function s(a){e([a.pageX,a.pageY])}
function j(a){var b=a.changedTouches;a.preventDefault();0<b.length&&e([b[0].pageX,b[0].pageY])}function l(a){A&&b([a.pageX,a.pageY])}function p(a){var e=a.changedTouches;a.preventDefault();A&&0<e.length&&b([e[0].pageX,e[0].pageY])}function m(){A&&h()}function u(a){a.preventDefault();A&&h()}var v,o=[0,0],r=[0,0],y=g.create([0,0],[0,0]),D,w=n,A=t,x=1,B,z,E;c.B(function(){var a=document.getElementById("rubberBandCanvas");a.addEventListener("mousedown",s);a.addEventListener("touchstart",j);window.addEventListener("mousemove",
l);window.addEventListener("touchmove",p);window.addEventListener("mouseup",m);window.addEventListener("touchend",u);window.addEventListener("touchcancel",u)});return Object.create(i.create(),{a:{value:function(){var a=document.getElementById("rubberBandCanvas");this.A&&(this.z(a),this.r&&(w=n));if(w){var b=a.getContext("2d");a.height=a.width=v;x=0.005*v;b.strokeStyle="#fff";b.lineWidth=x;b.lineJoin="round";b.strokeRect(o[0],o[1],r[0]-o[0],r[1]-o[1]);w=t}}},F:{get:function(){return A}},c:{set:function(a){a!==
v&&(v=a,w=n)}},aa:{set:function(a){z=a}},Z:{set:function(a){B=a}},$:{set:function(a){E=a}}})});
define("rot_anim_canvas",["boards","display_c_sys","display_canvas_factory"],function(c,g,a){var i,f,d,e,b,h,s,j,l;return Object.create(a.create(),{a:{value:function(){var a=document.getElementById("rotAnimCanvas");this.A&&this.z(a);if(d)if(s=h+0.004*j*(Date.now()-b),(0>j?0>=s:0<=s)&&(s=0),0>j?0>=s:0<=s)d=t,this.f();else{var c,l=a.getContext("2d");c=e[0][0];var v=e[0][1],o=e[1][0],r=e[1][1],y=g.s(e.S),y=[y[0]+g.n/2,y[1]+g.n/2];a.width=a.height=i;l.save();l.translate(y[0],y[1]);l.rotate(s);for(a=c;a<=
o;a+=1)for(c=v;c<=r;c+=1){var D=l,w=[a,c],A=y,x=g.s(w),B=g.n;D.fillStyle=f[w[0]][w[1]].color;D.fillRect(x[0]-A[0],x[1]-A[1],B,B)}l.restore()}}},c:{set:function(a){i=a}},o:{get:function(){return d}},Y:{value:function(a){return e.contains(a)}},M:{value:function(a){l=c.selected;f=l.g.copy();e=a.e;d=n;b=Date.now();j=-a.direction;h=a.P;this.show()}}})});
define("arrow_canvas",["display_c_sys","display_canvas_factory"],function(c,g){var a,i=t,f,d;d=Object.create(g.create(),{a:{value:function(){var e=document.getElementById("arrowCanvas");this.A&&(this.z(e),this.r&&(i=n));if(i){var b=e.getContext("2d");e.height=e.width=a;if(f!==k&&f.G){var g=f.O,d=c.s(f.e[1]),e=d[0],d=d[1],j=c.n/14;b.lineWidth=j;var l=90===g||-90===g?Math.PI/2:Math.PI;b.beginPath();b.arc(e+10*j,d+10*j,1.5*j,0,l);b.stroke();b.beginPath();90===g||180===g||-180===g?(g=-180===g?-3*j:0,
b.moveTo(e+10*j+g,d+10*j),b.lineTo(e+13*j+g,d+10*j),b.lineTo(e+11.5*j+g,d+8*j),b.lineTo(e+10*j+g,d+10*j)):(b.moveTo(e+10*j,d+10*j),b.lineTo(e+8*j,d+11.5*j),b.lineTo(e+10*j,d+13*j),b.lineTo(e+10*j,d+10*j));b.fill();b.closePath()}i=t}}},rotation:{set:function(a){if(f===k||!f.q(a))f=a,this.r&&(i=n)}},c:{set:function(c){c!==a&&(a=c,this.r&&(i=n))}}});d.f();return d});
define("rotation_factory",[],function(){var c=Object.create(q,{q:{value:function(c){return this.e.q(c.e)&&this.k===c.k}},G:{get:function(){return 0<this.e.j||0<this.e.l}},direction:{get:function(){return this.k?-1:1}},P:{get:function(){return this.direction*(this.e.u?Math.PI/2:Math.PI)}},O:{get:function(){return this.direction*(this.e.u?90:180)}},inverse:{get:function(){var g=this.e,a=!this.k;return Object.create(c,{e:{get:function(){return g}},k:{get:function(){return a}}})}}});return Object.create(q,
{create:{value:function(g,a){return Object.create(c,{e:{get:function(){return g}},k:{get:function(){return a}}})}}})});
define("tiles_canvas","boards rubber_band_canvas rot_anim_canvas arrow_canvas display_c_sys display_canvas_factory rotation_factory rect_t_factory".split(" "),function(c,g,a,i,f,d,e,b){function h(){o=m===k?k:e.create(m,u)}var s,j,l,p=n,m,u,v,o,r=n;g.aa=function(){i.show()};g.Z=function(a,b){if(m===k||!a.q(m)||b!==u){m=a;u=b;p=n;h();i.rotation=o}};g.$=function(){o!==k&&(o.G&&!c.selected.d)&&c.selected.rotate(o);c.selected.d?g.f():g.show();i.f();m=k;h();p=n};return Object.create(d.create(),{a:{value:function(){var d;
if(l===k||l!==c.selected){p=n;l=c.selected;d=n}else d=t;if(j===k||!l.g.Q(j)){j=l.g.copy();if(!d){d=l.m;d!==q&&a.M(d)}c.selected.d?g.f():g.show();i.f();p=n}if(r){d=e.create(b.create([0,0],[j.j-1,j.l-1]),n);a.M(d);r=t}if(v===k||v!==a.o){p=n;v=a.o}if(p){var h,o;d=l.t;h=document.getElementById("tilesCanvas");var u=h.getContext("2d"),x=l.d&&!a.o;h.height=h.width=s;x&&f.V();for(h=0;h<d;h=h+1)for(o=0;o<d;o=o+1){var B=u,z=[h,o],E=f.s(z),H=j[z[0]][z[1]].color,I=g.F,F=f.n,G=f.fa===0?1:0;if(!a.o||!a.Y(z)){B.globalAlpha=
I&&g.F&&m!==k&&z[0]>=m[0][0]&&z[0]<=m[1][0]&&z[1]>=m[0][1]&&z[1]<=m[1][1]?0.5:1;B.fillStyle=H;B.fillRect(E[0],E[1],F+G,F+G)}}x&&f.W();p=t}}},c:{set:function(a){if(a!==s){s=a;p=n}}}})});
define("display",["tiles_canvas","arrow_canvas","rubber_band_canvas","rot_anim_canvas","display_c_sys"],function(c,g,a,i,f){var d=t,e,b=n;return Object.create(q,{a:{value:function(){if(d){if(b){var h=document.getElementById("display").style;d&&(h.display="block");h.width=e+"px";h.height=e+"px";b=t}f.a();c.a();g.a();a.a();i.a()}}},c:{set:function(d){d!==e&&(e=d,f.c=e,c.c=e,g.c=e,a.c=e,i.c=e,b=n)}},show:{value:function(){b=d=n}}})});
define("board_thumb_factory",["boards"],function(c){function g(a,c,f){return a.map(function(a){return a*c/f})}return Object.create(q,{create:{value:function(a,i){var f=document.createElement("canvas"),d=n,e=0,b=0,h=0;f.addEventListener("click",function(){c.L=a;i()});return Object.create(q,{element:{get:function(){return f}},R:{set:function(b){b!==a&&(a=b,d=n)}},c:{set:function(a){a!==e&&(e=a,d=n)}},x:{set:function(a){a!==b&&(b=a,d=n)}},y:{set:function(a){a!==h&&(h=a,d=n)}},a:{value:function(){if(d){var i=
c[a],j=e,l=b,p=h,m=i.t,u=f.getContext("2d");f.width=f.height=j;f.style.left=l-j/2+"px";f.style.top=p-j/2+"px";for(l=0;l<m;l+=1)for(p=0;p<m;p+=1){var v=u,o=[l,p],r=j,y=i.t,D=i.D,w=g(o,r,y),r=r/y+1;v.fillStyle=D[o[0]][o[1]].color;v.fillRect(w[0],w[1],r,r)}d=t}}}})}}})});
define("boards_navigator",["boards","board_thumb_factory"],function(c,g){function a(){var a;d.forEach(function(b,c){a=c-u-e;b.c=f/(4+2*Math.abs(a));b.x=a*(f/3)+f/2;b.y=f/8})}function i(a){return g.create(((l+a)%c.length+c.length)%c.length,function(){b=e-a;h=0<b?-1:1;j=Date.now();s=n;l=c.L;d.forEach(function(a,b){a.R=((l+(b-u))%c.length+c.length)%c.length})})}var f,d=[],e=0,b,h,s=t,j,l=0,p=n,m=n,u=2;return Object.create(q,{a:{value:function(){if(m){var c=document.getElementById("boardsNavigator"),
g=c.style;g.width=f+"px";g.height=f/4+"px";p&&0<d.length&&(d.forEach(function(a){c.appendChild(a.element)}),p=t);m=t}d.forEach(function(a){a.a()});if(s){e=b+0.005*h*(Date.now()-j);if(0<h&&0<=e||0>h&&0>=e)e=0,s=t;a();a()}}},N:{value:function(){var b;d.length=0;for(b=-u;b<=u;b+=1)d.push(i(b));a();m=n}},width:{set:function(b){b!==f&&(f=b,a(),m=n)}}})});
define("hiscores_table",["util","boards"],function(c,g){function a(a){var b=document.createElement("td");b.appendChild(document.createTextNode(a));return b}function i(b){var c=document.createElement("tr");c.appendChild(a(b.name));c.appendChild(a(b.b));return c}function f(){p.h.I=m.value}function d(){o&&(p.h.I=m.value,p.h.ea(),r=n)}function e(){var a;u!==k&&(a="submit button"+(o?"":" disabled"),u.className=a)}function b(){o=""!==m.value;e()}function h(a){b();13===a.keyCode&&d()}function s(a){var c=
document.createElement("td");m===k&&(m=document.createElement("input"),m.type="text",m.maxLength=m.size=p.h.H,m.spellcheck=t,m.addEventListener("blur",f),m.addEventListener("keyup",h),m.addEventListener("propertychange",b),m.addEventListener("input",b),m.addEventListener("paste",b));m.value=a;c.appendChild(m);b();return c}function j(){var a=document.createElement("td");u===k&&(u=document.createElement("span"),u.appendChild(document.createTextNode("\u21b5")),u.addEventListener("click",d),e());a.appendChild(u);
return a}function l(a){var b=document.createElement("tr");b.className="input";b.appendChild(s(a.name));b.appendChild(j());return b}var p,m,u,v,o=t,r=n;return Object.create(q,{a:{value:function(){g.selected!==p?(p=g.selected,v=p.d,r=n):p.d!==v&&(v=p.d,r=n);if(r){var a=document.getElementById("hiscoresTable");c.clear(a);p.h.forEach(function(b,c,d){d?a.appendChild(l(b)):a.appendChild(i(b))});r=t}}}})});
define("rotations_navigator",["boards","util"],function(c,g){function a(a){return document.querySelector("#rotationsNavigator>."+a+".button")}function i(){b.w()}function f(){b.v()}function d(b,c){var d=b+" button";c&&(d+=" disabled");a(b).className=d}var e,b,h=n;g.B(function(){a("undo").addEventListener("click",i);a("redo").addEventListener("click",f)});return Object.create(q,{a:{value:function(){c.selected!==b&&(b=c.selected,h=n);b.b!==e&&(e=b.b,h=n);h&&(document.getElementById("nRotations").textContent=
e,d("undo",!b.ga),d("redo",!b.ca),h=t)}}})});
define("panel",["boards_navigator","hiscores_table","rotations_navigator"],function(c,g,a){var i,f,d=n,e=t;return Object.create(q,{a:{value:function(){if(e){if(d){var b=document.getElementById("panel").style;b.display="block";b.width=i+"px";b.height=f+"px";b.left=f+"px";b.fontSize=Math.ceil(f/25)+"px";d=t}c.a();g.a();a.a()}}},show:{value:function(){e=n;c.N();d=n}},width:{set:function(a){a!==i&&(i=a,c.width=i,d=n)}},height:{set:function(a){a!==f&&(f=a,d=n)}}})});
define("load_indicator",[],function(){var c=n,g=n,a;return Object.create(q,{a:{value:function(){if(c&&g){var i=document.getElementById("loadIndicator").style;i.fontSize=Math.ceil(a/20)+"px";i.top=i.left=Math.round(0.01*a);i.display="block";g=t}}},f:{value:function(){document.getElementById("loadIndicator").style.display="none";c=t}},width:{set:function(c){c!==a&&(a=c,g=n)}}})});
define("../vendor/rAF",[],function(){for(var c=0,g=["ms","moz","webkit","o"],a=0;a<g.length&&!window.requestAnimationFrame;++a)window.requestAnimationFrame=window[g[a]+"RequestAnimationFrame"],window.C=window[g[a]+"CancelAnimationFrame"]||window[g[a]+"CancelRequestAnimationFrame"];window.requestAnimationFrame||(window.requestAnimationFrame=function(a){var f=(new Date).getTime(),d=Math.max(0,16-(f-c)),e=window.setTimeout(function(){a(f+d)},d);c=f+d;return e});window.C||(window.C=function(a){clearTimeout(a)})});
define("game","display panel boards load_indicator util ../vendor/rAF".split(" "),function(c,g,a,i,f){function d(){i.a();c.a();g.a();window.requestAnimationFrame(d)}function e(){if(window.innerWidth/window.innerHeight<1.61803398875){b=window.innerWidth;h=Math.floor(b/1.61803398875)}else{h=window.innerHeight;b=Math.floor(h*1.61803398875)}document.body.style.width=b+"px";document.body.style.height=h+"px";c.c=h;g.width=b-h;g.height=h;i.width=b}var b,h;f.B(function(){window.requestAnimationFrame(d);a.load(function(){g.show();
c.show();i.f()});e();window.addEventListener("resize",e)})});